from selenium import webdriver
from selenium.webdriver.common.by import By
driver_1 = webdriver.Chrome()
driver_1.maximize_window()
driver_1.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
driver_1.implicitly_wait(20)
driver_1.find_element(By.XPATH, "//input[@placeholder='Username']").send_keys("Admin")
driver_1.implicitly_wait(20)
driver_1.find_element(By.XPATH, "//*[@type='password']").send_keys("admin123")
driver_1.find_element(By.XPATH, "//*[@type='submit']").click()
driver_1.implicitly_wait(20)
driver_1.find_element(By.XPATH, "(//span[@class='oxd-text oxd-text--span oxd-main-menu-item--name'])[2]").click()
driver_1.find_element(By.LINK_TEXT, "Add Employee").click()
driver_1.implicitly_wait(20)
driver_1.find_element(By.NAME, "firstName").send_keys("Amar")
driver_1.implicitly_wait(20)
driver_1.find_element(By.NAME, "middleName").send_keys("LAXMAN")
driver_1.find_element(By.NAME, "lastName").send_keys("KAMAT")
driver_1.find_element(By.XPATH,"(//*[@class='oxd-input oxd-input--active'])[1]").send_keys("101")
driver_1.implicitly_wait(20)
driver_1.find_element(By.XPATH, "//*[@type='submit']").click()
print(" employee Added Successfully")
